/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package meadowhawk.piserver

import io.prometheus.client.CollectorRegistry
import io.prometheus.client.hotspot.DefaultExports
import meadowhawk.piserver.service.PrometheusService

import static spark.Spark.*
import meadowhawk.piserver.service.ZoomService

class App {
    static String getGreeting() {
        return '<H2>Welcome to Zoom Status API v1.0</H2><H3>API</H3> <ul><li>View call Logs - GET /zoom/status</li><li>Toggle LED - POST /zoom/status/update?callStatus=on|off</li></ul>'
    }

    static final String JSON_TYPE = "application/json"
    static ZoomService zoomService = new ZoomService()
    static PrometheusService prometheusSvc =  new PrometheusService(zoomService)

    static void main(String[] args) {
        println "Starting server...."
        DefaultExports.initialize()

        get '/', { req, res -> getGreeting() }
        get '/zoom', { req, res -> getGreeting() }
        get '/zoom/status', { req, res ->
            res.status(200)
            res.type(JSON_TYPE)
            zoomService.getStatusInfo()
        }
        post '/zoom/status/update', { req, res ->
            zoomService.toggleIndicator(req)
            res.type(JSON_TYPE)
            res.status(200)
            ""
        }

        get '/prometheus', { req, res -> prometheusSvc.getMetrics(res) }

    }
}
